[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

  [buildPlans.iosevka-custom.variants]
  inherits = "ss09"

    [buildPlans.iosevka-custom.variants.design]
    capital-d = "standard-serifless"
    f = "flat-hook"
    j = "flat-hook-serifed"
    t = "flat-hook-short-neck"
    zero = "slashed-oval"
    one = "base"
    four = "semi-open"
    five = "vertical-upper-left-bar"
    brace = "straight"
    dollar = "through"
    percent = "rings-continuous-slash"
    lig-ltgteq = "slanted"

  [buildPlans.iosevka-custom.ligations]
  inherits = "clike"

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-custom.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"