#!/usr/bin/env bash
# A script for nerd fonts patching,
# can not be used for gnome terminal for now

# ===============================
# Output folder
DIR="Custom NF"
# Output folder which generated by 'custom.sh'
OPUTDIR="FiraCode Custom"
# ===============================

# check
clear
cd ~ || exit
if ! docker --version &> /dev/null; then
    echo "Please install docker!"
    exit 1
fi
if [[ ! -d ${OPUTDIR} ]]; then
    echo "Please run 'custom.sh' first."
    exit 1
fi

# 1. Build nerd fonts
# https://github.com/ryanoasis/nerd-fonts#option-8-patch-your-own-font
clear
echo "Build nerd fonts..."
rm -rf "${DIR}" && mkdir -p "${DIR}/${OPUTDIR}"
mkdir "${DIR}/${OPUTDIR}/nf" "${DIR}/${OPUTDIR}/nf-mono" "${DIR}/${OPUTDIR}/nf-windows" "${DIR}/${OPUTDIR}/nf-windows-mono"

docker run --rm -v "${PWD}/${OPUTDIR}":/in -v "${PWD}/${DIR}/${OPUTDIR}/nf":/out nerdfonts/patcher -c -l --careful
docker run --rm -v "${PWD}/${OPUTDIR}":/in -v "${PWD}/${DIR}/${OPUTDIR}/nf-mono":/out nerdfonts/patcher -s -c -l --careful
docker run --rm -v "${PWD}/${OPUTDIR}":/in -v "${PWD}/${DIR}/${OPUTDIR}/nf-windows":/out nerdfonts/patcher -c -l -w --careful
docker run --rm -v "${PWD}/${OPUTDIR}":/in -v "${PWD}/${DIR}/${OPUTDIR}/nf-windows-mono":/out nerdfonts/patcher -s -c -l -w --careful

# 2. change owner and group
clear
echo "Change the owner and group to you..."
for file in "${DIR}/${OPUTDIR}"/nf*/*.ttf; do
    sudo chown "$(whoami)" "${file}"
    sudo chgrp "$(whoami)" "${file}"
done
# compress files
if zip --help &> /dev/null; then
    zip -q -r "${DIR}.zip" "${DIR}"
else
    tar -cf "${DIR}.tar" "${DIR}"
fi
clear
echo "A compressed file of '${DIR}' has been generated."
